# Generated by Django 6.1 on 2026-08-19 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="technology",
            options={"verbose_name_plural": "Technologies"},
        ),
    ]
