# Generated by Django 6.1 on 2026-09-13 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_alter_technology_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectdetail",
            name="demo_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
