# Generated by Django 6.1 on 2026-09-24 09:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_alter_projectdetail_demo_link"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="project",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2026, 9, 24, 9, 34, 48, 701354, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
    ]
