# Generated by Django 6.1 on 2026-08-19 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("role_title", models.CharField(max_length=100)),
                ("subtitle", models.CharField(blank=True, max_length=100)),
                ("bio", models.TextField()),
                ("is_available", models.BooleanField(default=True)),
                ("availability_label", models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="SiteDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("R", "Resume"),
                            ("C", "Contract"),
                            ("T", "Tariff"),
                            ("P", "Packages"),
                        ],
                        max_length=1,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("file", models.FileField(upload_to="documents/")),
            ],
        ),
    ]
