# Generated by Django 6.1 on 2026-09-02 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="image",
            field=models.ImageField(default="", upload_to="profile/"),
            preserve_default=False,
        ),
    ]
