# Generated by Django 6.1 on 2026-09-02 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("experience", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="experience",
            options={"ordering": ["-year"]},
        ),
    ]
