# Generated by Django 6.1 on 2026-09-24 10:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("experience", "0002_alter_experience_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="experience",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="experience",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2026, 9, 24, 10, 48, 23, 619587, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
    ]
